### ISSUE TITLE
Hotkey does not work to set a comment.

### ISSUE THREAD

**Issue by Hammer2900** [foxoman/zed-nim#13]
I tried to set the comment in nim file when pressing ctrl+/ and even when you change the hotkey the comment is
not set, if you take another language and try to comment out the code there everything works fine, as I 
understand in the plugin there is no configuration how to set a comment like here
https://github.com/sweetppro/zed-xml/blob/main/languages/xml/config.toml

**Comment by foxoman** [comment]
Thank you for reporting, I will take a look on it
