### ISSUE TITLE
Loss of Syntax Highlighting with Nim String Interpolation

### ISSUE THREAD

**Issue by foxoman** [foxoman/zed-nim#3]
#### Description

I write the bugs I notice myself to work on fixing them or by contributors.

For this bug, I noticed an issue related to syntax highlighting for string interpolation. 

Here's a code snippet that works fine:
```nim
echo(fmt "{person.name} is {person.age} years old")
```
The syntax highlighting is correct in this case.

However, if I remove the space between `fmt` and the string, the string loses its syntax highlighting:
```nim
echo(fmt"{person.name} is {person.age} years old")
```

#### Steps to Reproduce

1. Write the following code in the Zed editor with the Nim extension installed:
   ```nim
   echo(fmt "{person.name} is {person.age} years old")
   ```
![image](https://github.com/user-attachments/assets/9cf47081-9e56-466f-a2cf-86be97bc2220)

2. Observe the syntax highlighting.
3. Modify the code by removing the space between `fmt` and the string:
   ```nim
   echo(fmt"{person.name} is {person.age} years old")
   ```
![image](https://github.com/user-attachments/assets/cd850ff5-d098-4014-b244-31cc41cc7fc7)

4. Observe the loss of syntax highlighting.

#### Expected Behavior

The string should maintain its syntax highlighting regardless of the presence of a space between `fmt` and the string.

#### Actual Behavior

The string loses its syntax highlighting when the space between `fmt` and the string is removed.

**Comment by tigormal** [comment]
So, nim_format_string tree-sitter grammar [exists](https://github.com/aMOPel/tree-sitter-nim-format-string.git). I have tried adding it to the extension, and it works on it's own (I can make a pull request as is if necessary). However for some reason it doesn't appear injected in `fmt"..."` strings. Changing injection language to "nim" works ok, so the queries in injections.scm are in fact correct, but Zed doesn't allow using neighbouring grammars from within one extension. Maybe some config file has to be modified in a way to allow this?

**Comment by foxoman** [comment]
Thank you very much for your support and trying to find a solution, and yes
the Grammer is correct , it worked in nvim as I use it, but does not work
in zed , will try to find if other languages have same issues or any update
from zed to solve it.

If you find a way, you can for sure submit a pull request even if not
complete.

Appreciate your help.

**Comment by tigormal** [comment]
I found what the problem is with tree-sitter-nim-format-string grammar. Zed, apparently, doesn't allow grammar names with underscores in it. Replacing "nim_format_string" with "nimstrfmt" in all of it's code and in injections.scm fixed the issue, but it's clearly not a good way to go, and I'm not sure what to do about it. 
<img width="436" alt="Screenshot 2024-11-02 at 19 56 00" src="https://github.com/user-attachments/assets/8cbe838e-d4c0-4a3d-b794-41d5561a1155">
