### ISSUE TITLE
LSP not working?

### ISSUE THREAD

**Issue by casey-SK** [foxoman/zed-nim#5]
I am able to install this extension within the app. I am able to use the tasks provided by the extension. But anything to do with syntax doesn't seem to work. No inline hints, No LSP errors.

**Comment by casey-SK** [comment]
Helps if you have the [language server](https://github.com/nim-lang/langserver) installed :/

`nimble install nimlangserver`

**Comment by felipetesc** [comment]
Not working to me as well. I have nimlangserver installed and correctly added to the path.
```bash

> nimlangserver --version
1.6.0

```

**Comment by felipetesc** [comment]
I've changed the zed_extension_api from 0.06 to 0.1.0 inside Cargo.toml and I`ve found no error after that.
