### ISSUE TITLE
Code fold indenting does not indent folded code

### ISSUE THREAD

**Issue by cvanelteren** [foxoman/zed-nim#9]
When fold in a function and then moving the function, it does not indent the code under that fold. Only the top most level gets moved correctly.

**Comment by foxoman** [comment]
Can you share photo or video please.

**Comment by cvanelteren** [comment]
Think this was a me problem, apologies! --> there is an issue where pasting code is using the prior heading but not sure if this is a nim-mode issue. Closing for now.
